apiVersion: v1
kind: Service
metadata: 
   name: jenkins-service
   labels:
      name: jenkins-service
spec:
  type: LoadBalancer
  selector:
     name: jenkins
     app: jenkins-ci
  ports:
   - port: 8080
     targetPort: 8080
